FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TaskHandler-Services-Infrastructure.csproj", "TaskHandler-Services-Infrastructure.API/"]

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TaskHandler-Services-Infrastructure.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskHandler-Services-Infrastructure.dll"]